name: 'Test suite'
on:
    - push
jobs:
    makefile:
        runs-on: ubuntu-latest
        steps:
            - {name: Checkout, uses: actions/checkout@v1}
            - {name: 'Show HELP', run: 'make help'}
            - {name: 'npm install', run: 'npm clean-install'}
